version: "3.9"
services:
  sql-server-container-name:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    volumes: 
      - sql-server-volume-name:/var/opt/mssql
      - ${USERPROFILE}\.aspnet\https:/https/
    environment:
      MSSQL_SA_PASSWORD: ""
      ACCEPT_EULA: Y
    networks:
      network-name:
        aliases:
          - sql-server-name

  api-container-name:
    image: api
    ports:
      - "7000:80"
      - "7001:443"
    volumes: 
      - ${USERPROFILE}\.aspnet\https:/https/
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: 7001
      ASPNETCORE_Kestrel__Certificates__Default__Password: ""
      ASPNETCORE_ENVIRONMENT: Container 
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/api-server.pfx
    networks:
      network-name:
        aliases:
          - api-server-name


volumes:
  sql-server-volume-name:

networks:
  network-name: {} 



